import { db, assertFirebaseConfigured } from './firebase-config.js';
import { readableAuthError, requireAdmin, showToast } from './auth.js';
import { escapeHtml, getAllMovies, validHttpsUrl } from './movies.js';
import { addDoc, collection, deleteDoc, doc, getDoc, getDocs, serverTimestamp, setDoc, updateDoc } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js';

let adminUser;
let movies = [];
function field(id) { return document.querySelector('#' + id); }
function message(selector, text, type) { const box = document.querySelector(selector); if (!box) return; box.textContent = text || ''; box.className = text ? 'form-message ' + (type || 'error') : 'form-message hidden'; }
function payload() { return { titulo: field('movieTitle').value.trim(), sinopsis: field('movieSynopsis').value.trim(), año: Number(field('movieYear').value), duracion: field('movieDuration').value.trim(), genero: field('movieGenre').value.trim(), posterUrl: field('moviePoster').value.trim(), bannerUrl: field('movieBanner').value.trim(), linkUrl: field('movieLink').value.trim(), trailerUrl: field('movieTrailer').value.trim(), destacada: field('movieFeatured').checked, actualizadoEn: serverTimestamp() }; }
function validate(data) { if (!data.titulo || !data.sinopsis || !data.año || !data.duracion || !data.genero) return 'Completa los campos obligatorios.'; if (data.año < 1888 || data.año > 2100) return 'El año no es válido.'; if (!validHttpsUrl(data.posterUrl) || !validHttpsUrl(data.bannerUrl) || !validHttpsUrl(data.linkUrl)) return 'Las URLs principales deben comenzar con https://.'; if (data.trailerUrl && !validHttpsUrl(data.trailerUrl)) return 'La URL del tráiler no es válida.'; return ''; }
function reset() { field('movieForm').reset(); field('movieId').value = ''; field('movieFormTitle').textContent = 'Agregar película'; field('cancelEdit').classList.add('hidden'); message('#movieFormMessage', ''); }
function editMovie(movie) { field('movieId').value = movie.id; field('movieTitle').value = movie.titulo || ''; field('movieSynopsis').value = movie.sinopsis || ''; field('movieYear').value = movie.año || ''; field('movieDuration').value = movie.duracion || ''; field('movieGenre').value = movie.genero || ''; field('moviePoster').value = movie.posterUrl || ''; field('movieBanner').value = movie.bannerUrl || ''; field('movieLink').value = movie.linkUrl || ''; field('movieTrailer').value = movie.trailerUrl || ''; field('movieFeatured').checked = movie.destacada === true; field('movieFormTitle').textContent = 'Editar película'; field('cancelEdit').classList.remove('hidden'); window.scrollTo({ top: 0, behavior: 'smooth' }); }
function renderMovies() { const list = field('adminMoviesList'); if (!movies.length) { list.innerHTML = '<div class="empty-state">Todavía no hay películas.</div>'; return; } list.innerHTML = movies.map(function(movie) { return '<article class="admin-movie-item"><img src="' + escapeHtml(movie.posterUrl || '') + '" alt=""><div><h3>' + escapeHtml(movie.titulo || '') + '</h3><p>' + escapeHtml(movie.año || '') + ' · ' + escapeHtml(movie.genero || '') + '</p></div><div class="item-actions"><button class="btn btn-secondary btn-small" data-edit="' + movie.id + '" type="button">Editar</button><button class="btn btn-danger btn-small" data-delete="' + movie.id + '" type="button">Eliminar</button></div></article>'; }).join(''); list.querySelectorAll('[data-edit]').forEach(function(button) { button.addEventListener('click', function() { editMovie(movies.find(function(movie) { return movie.id === button.dataset.edit; })); }); }); list.querySelectorAll('[data-delete]').forEach(function(button) { button.addEventListener('click', async function() { const movie = movies.find(function(item) { return item.id === button.dataset.delete; }); if (!movie || !confirm('¿Eliminar ' + movie.titulo + '?')) return; try { await deleteDoc(doc(db, 'movies', movie.id)); movies = await getAllMovies(); renderMovies(); showToast('Película eliminada.'); } catch (error) { showToast(readableAuthError(error), true); } }); }); }
async function saveMovie(event) { event.preventDefault(); const data = payload(); const errorText = validate(data); if (errorText) { message('#movieFormMessage', errorText); return; } try { const id = field('movieId').value; if (data.destacada) await Promise.all(movies.filter(function(item) { return item.id !== id && item.destacada; }).map(function(item) { return updateDoc(doc(db, 'movies', item.id), { destacada: false }); })); if (id) await updateDoc(doc(db, 'movies', id), data); else await addDoc(collection(db, 'movies'), Object.assign({}, data, { creadoEn: serverTimestamp() })); movies = await getAllMovies(); renderMovies(); reset(); showToast('Película guardada.'); } catch (error) { message('#movieFormMessage', readableAuthError(error)); } }
function dateText(value) { if (!value) return '—'; const date = value.toDate ? value.toDate() : new Date(value); return date.toLocaleDateString('es-CO'); }
async function loadUsers() { const result = await getDocs(collection(db, 'users')); const list = field('usersList'); const users = result.docs.map(function(item) { return Object.assign({ id: item.id }, item.data()); }); list.innerHTML = '<table class="admin-table"><thead><tr><th>Usuario</th><th>Registro</th><th>Rol</th><th>Estado</th><th>Acción</th></tr></thead><tbody>' + users.map(function(user) { const own = user.id === adminUser.uid; return '<tr><td><strong>' + escapeHtml(user.nombre || '') + '</strong><br><span class="muted">' + escapeHtml(user.email || '') + '</span></td><td>' + dateText(user.fechaRegistro) + '</td><td><select data-role="' + user.id + '" ' + (own ? 'disabled' : '') + '><option value="user" ' + (user.rol === 'user' ? 'selected' : '') + '>Usuario</option><option value="admin" ' + (user.rol === 'admin' ? 'selected' : '') + '>Admin</option></select></td><td><span class="status-pill ' + (user.bloqueado ? 'blocked' : 'active') + '">' + (user.bloqueado ? 'Bloqueado' : 'Activo') + '</span></td><td><button class="btn btn-secondary btn-small" data-block="' + user.id + '" ' + (own ? 'disabled' : '') + ' type="button">' + (user.bloqueado ? 'Desbloquear' : 'Bloquear') + '</button></td></tr>'; }).join('') + '</tbody></table>'; list.querySelectorAll('[data-role]').forEach(function(select) { select.addEventListener('change', async function() { await updateDoc(doc(db, 'users', select.dataset.role), { rol: select.value }); await loadUsers(); showToast('Rol actualizado.'); }); }); list.querySelectorAll('[data-block]').forEach(function(button) { button.addEventListener('click', async function() { const ref = doc(db, 'users', button.dataset.block); const snap = await getDoc(ref); await updateDoc(ref, { bloqueado: !snap.data().bloqueado }); await loadUsers(); showToast('Estado actualizado.'); }); }); }
async function loadSettings() { const result = await getDoc(doc(db, 'settings', 'site')); if (result.exists()) { field('globalBanner').value = result.data().bannerUrl || ''; field('globalBackground').value = result.data().fondoUrl || ''; } }
async function saveSettings(event) { event.preventDefault(); const bannerUrl = field('globalBanner').value.trim(); const fondoUrl = field('globalBackground').value.trim(); if ((bannerUrl && !validHttpsUrl(bannerUrl)) || (fondoUrl && !validHttpsUrl(fondoUrl))) { message('#settingsMessage', 'Las URLs deben comenzar con https://.'); return; } await setDoc(doc(db, 'settings', 'site'), { bannerUrl: bannerUrl, fondoUrl: fondoUrl, actualizadoEn: serverTimestamp() }, { merge: true }); message('#settingsMessage', 'Configuración guardada.', 'success'); }
function tabs() { document.querySelectorAll('.admin-tab').forEach(function(button) { button.addEventListener('click', function() { document.querySelectorAll('.admin-tab,.admin-tab-panel').forEach(function(item) { item.classList.remove('active'); }); button.classList.add('active'); document.querySelector('#' + button.dataset.tab).classList.add('active'); }); }); }
async function init() { try { assertFirebaseConfigured(); const state = await requireAdmin(); if (!state) return; adminUser = state.user; movies = await getAllMovies(); renderMovies(); await Promise.all([loadUsers(), loadSettings()]); field('movieForm').addEventListener('submit', saveMovie); field('cancelEdit').addEventListener('click', reset); field('settingsForm').addEventListener('submit', saveSettings); tabs(); field('adminLoading').classList.add('hidden'); field('adminPanel').classList.remove('hidden'); } catch (error) { field('adminLoading').innerHTML = '<div class="empty-state">' + escapeHtml(error.message) + '<br><br><a class="btn btn-secondary" href="index.html">Volver</a></div>'; } }
if (document.body.dataset.page === 'admin') init();
